export const currencies = [
  { shortName: "USD", fullName: "United States Dollar" },
  { shortName: "EUR", fullName: "Euro" },
  { shortName: "JPY", fullName: "Japanese Yen" },
  { shortName: "GBP", fullName: "British Pound Sterling" },
  { shortName: "AUD", fullName: "Australian Dollar" },
  { shortName: "CAD", fullName: "Canadian Dollar" },
  { shortName: "CHF", fullName: "Swiss Franc" },
  { shortName: "CNY", fullName: "Chinese Yuan" },
  { shortName: "HKD", fullName: "Hong Kong Dollar" },
  { shortName: "NZD", fullName: "New Zealand Dollar" },
  { shortName: "SEK", fullName: "Swedish Krona" },
  { shortName: "KRW", fullName: "South Korean Won" },
  { shortName: "SGD", fullName: "Singapore Dollar" },
  { shortName: "NOK", fullName: "Norwegian Krone" },
  { shortName: "MXN", fullName: "Mexican Peso" },
  { shortName: "INR", fullName: "Indian Rupee" },
  { shortName: "RUB", fullName: "Russian Ruble" },
  { shortName: "ZAR", fullName: "South African Rand" },
  { shortName: "BRL", fullName: "Brazilian Real" },
  { shortName: "TRY", fullName: "Turkish Lira" },
  { shortName: "TWD", fullName: "Taiwan New Dollar" },
  { shortName: "DKK", fullName: "Danish Krone" },
  { shortName: "PLN", fullName: "Polish Zloty" },
  { shortName: "THB", fullName: "Thai Baht" },
  { shortName: "IDR", fullName: "Indonesian Rupiah" },
  { shortName: "HUF", fullName: "Hungarian Forint" },
  { shortName: "CZK", fullName: "Czech Koruna" },
  { shortName: "ILS", fullName: "Israeli New Shekel" },
  { shortName: "CLP", fullName: "Chilean Peso" },
  { shortName: "PHP", fullName: "Philippine Peso" },
  { shortName: "AED", fullName: "United Arab Emirates Dirham" },
  { shortName: "COl", fullName: "Colombian Peso" },
  { shortName: "SAR", fullName: "Saudi Riyal" },
  { shortName: "MYR", fullName: "Malaysian Ringgit" },
  { shortName: "EGP", fullName: "Egyptian Pound" },
  { shortName: "VND", fullName: "Vietnamese Dong" },
  { shortName: "NGN", fullName: "Nigerian Naira" },
  { shortName: "KES", fullName: "Kenyan Shilling" },
  { shortName: "PKR", fullName: "Pakistani Rupee" },
  { shortName: "IQD", fullName: "Iraqi Dinar" },
  { shortName: "ARS", fullName: "Argentine Peso" },
  { shortName: "COP", fullName: "Colombian Peso" },
  { shortName: "UAH", fullName: "Ukrainian Hryvnia" },
];
